global:
  scrape_interval: 15s  # How often to scrape targets
  scrape_timeout: 10s  # Timeout before considering a scrape failed
  evaluation_interval: 15s  # How often to evaluate rules

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets:
          - "localhost:9090"

  # Spring Boot Application (Tomcat Monitoring)
  - job_name: "tomcat-monitoring"
    honor_timestamps: true
    scrape_interval: 10s  # Faster updates for real-time tracking
    scrape_timeout: 5s
    metrics_path: "/actuator/prometheus"  # Endpoint for Spring Boot metrics
    scheme: http
    static_configs:
      - targets:
          - "192.168.65.254:8083"  # Update this if running on a different host

